language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

jobs:
  allow_failures:
  - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - composer update --prefer-dist

script:
  - ./bin/test.sh
